swagger: '2.0'
info:
  title: Twitter Troll and Bot Finder
  version: "1.0"
  description: |
    Analysis and classification of the behavoir of Twitter users according to
    five different profiles: drama queen, hater, stalker, bot and spammer.

# the domain of the service
host: 188.166.145.237
# array of all schemes that your API supports
schemes:
  - http
# will be prefixed to all paths
basePath: /v1
produces:
  - application/json
paths:

  /user/{user_id}:  
    get:
      tags:
        - User
      operationId: api.get_user
      summary: Get a single user
      parameters:
        - $ref: '#/parameters/user_id'
      responses:
        200:
          description: Return user
          schema:
            $ref: '#/definitions/User'
        404:
          description: User does not exist
        500:
          description: Server error

parameters:

  user_id:
    name: user_id
    description: Unique Twitter username
    in: path
    type: string
    required: true
   

definitions:
  User:
    type: object
    required:
      - user_id
    properties:
      user_id:
        type: string
        readOnly: true
        description: Unique user identifier
      bot:
        type: number
        format: float
      drama_queen:
        type: number
        format: float
      stalker:
        type: number
        format: float
      hater:
        type: number
        format: float
      spammer:
        type: number
        format: float
      famous:
        type: boolean
      non_famous:
        type: boolean
      stalked:
        type: string
      final:
        type: string



  Error:
    properties:
      code:
        type: "integer"
        format: int32
      message:
        type: string
      fields:
        type: string
